[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["assets/food_images/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200
  force = true
